# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-demo
  labels:
    app: prometheus-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-demo
  template:
    metadata:
      labels:
        app: prometheus-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: demo
        image: your-dockerhub-username/prometheus-client-hello
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-demo
  labels:
    app: prometheus-demo
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: prometheus-demo
