name: python-client-prometheus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# env:
#  dotnetVersion: '8.0'
        
permissions:
  packages: write
  

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Show directory
      run: |
        pwd
        ls -al -R
    
    # build dockerfile 
    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/prometheus-monitoring-hello:latest